# Generated by Django 5.1.1 on 2024-10-07 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="Назавание курса", max_length=50)),
                (
                    "course_preview",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="materials/course_previews",
                        verbose_name="Превью курса",
                    ),
                ),
                ("description", models.TextField(verbose_name="Содержание курса")),
            ],
            options={
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="Назавание урока", max_length=50)),
                ("description", models.TextField(verbose_name="Содержание урока")),
                (
                    "lesson_preview",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="materials/lesson_previews",
                        verbose_name="Превью урока",
                    ),
                ),
                (
                    "url_video",
                    models.URLField(
                        blank=True, null=True, verbose_name="Ссылка на видео"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="materials.course",
                        verbose_name="Курс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
            },
        ),
    ]
