# Generated by Django 5.1.1 on 2024-10-06 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_course_student_lesson_student"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="course_preview",
        ),
        migrations.RemoveField(
            model_name="course",
            name="student",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="lesson_preview",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="student",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="url_video",
        ),
        migrations.AddField(
            model_name="course",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="preview_course",
            field=models.ImageField(
                blank=True,
                help_text="Укажите превью",
                null=True,
                upload_to="materials/preview_course",
                verbose_name="Превью",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="link_to_video",
            field=models.CharField(
                blank=True,
                help_text="Укажите ссылку",
                max_length=100,
                null=True,
                verbose_name="Ссылка на видео",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="preview_lesson",
            field=models.ImageField(
                blank=True,
                help_text="Укажите превью",
                null=True,
                upload_to="materials/preview_lesson",
                verbose_name="Превью",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Укажите описание",
                null=True,
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(
                help_text="Укажите курс", max_length=100, verbose_name="Название курса"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите курс",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="materials.course",
                verbose_name="Название курса",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Укажите описание",
                null=True,
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="title",
            field=models.CharField(
                help_text="Укажите урок", max_length=100, verbose_name="Название урока"
            ),
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Курс",
                        to="materials.course",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Пользователь",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Подписка",
                "verbose_name_plural": "Подписки",
            },
        ),
    ]
